# Generated by Django 4.1.7 on 2023-06-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категоря',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('old', models.CharField(default='Для взрослых собак', max_length=25, verbose_name='Возраст')),
                ('ingredients', models.CharField(max_length=255, verbose_name='Ингредиенты')),
                ('breed', models.CharField(default='Для всех пород', max_length=25, verbose_name='Порода')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
